### PR TITLE
Update and rename data/18/02/2023/3/1260214523.geojson to données/12…

### PR DESCRIPTION
**Pull request by 622333371**
…6/021/452/3/1260214523.geojson

Rectification de nom et coordonnées exact s'il y a encore des erreurs vos successions sont les bienvenus

### CODE REVIEW

**Review by 5212BABA — APPROVED** [review]

**Review by 5212BABA — CHANGES_REQUESTED** [review]
Rectification de données data/126/021/452/3/1260214523.geojson → rectifier le nom tomba dougoula par tomba kanssa et les coordonnées

**Review by 5212BABA — APPROVED** [review]
Rectification du nom tomba dougoula par tomba kanssa et les coordonnées

**Comment by 5212BABA** [comment]
De 8cdc0bb865edb8cfd31521ca465a1a8eb2ca16e7 Lundi 17 sept. 00:00:00 2001
De : 622333371 <124220030+622333371@users.noreply.github.com>
Date : sam. 18 févr. 2023 23:09:17 +0000
Objet : [PATCH 1/2] =?UTF-8?q?Update=20and=20rename=20data/126/021/452/3/?=
 =?UTF-8?q?1260214523.geojson=20to=20donn=C3=A9es/126/021/452/3/1260214523?=
 =?UTF-8?q?.geojson?=
Version MIME : 1.0
Type de contenu : texte/plain ; jeu de caractères=UTF-8
Encodage de transfert de contenu : 8 bits

Rectification de nom et coordonnées exactes
---
 .../126/021/452/3/1260214523.geojson" | 30 +++++++++----------
 1 fichier modifié, 15 insertions(+), 15 suppressions(-)
 renommer data/126/021/452/3/1260214523.geojson => "donn\303\251es/126/021/452/3/1260214523.geojson" (76%)

diff --git a/data/126/021/452/3/1260214523.geojson "b/donn\303\251es/126/021/452/3/1260214523.geojson"
indice de similarité 76%
renommer à partir de data/126/021/452/3/1260214523.geojson
renommer en "donn\303\251es/126/021/452/3/1260214523.geojson"
indice 60b1c7f9..7fcd9338 100644
--- a/data/126/021/452/3/1260214523.geojson
+++ "b/donn\303\251es/126/021/452/3/1260214523.geojson"
@@ -7,24 +7,24 @@
     "geom:area":0.0,
     "géom:area_square_m":0.0,
     "geom:bbox":"-10.2,11.73333,-10.2,11.73333",
- "géom:latitude":11.73333,
- "géom:longitude":-10.2,
+ "géom:latitude":11.7273973,
+ "géom:longitude":-10.18,
     "gn:admin1_code":"K",
     "gn:admin2_code":"07",
- "gn:asciiname":"Tomba Dougoula",
+ "gn:asciiname":"Tomba kanssa",
     "gn:country_code":"GN",
- "gn:dem":403,
+ "gn:dem":430,
     "gn:feature_class":"P",
     "gn:feature_code":"PPL",
     "gn:geonameid":2414641,
- "gn:latitude":11.73333,
- "gn:longitude":-10.2,
- "gn:modification_date":"2013-08-06",
- "gn:name":"Tomba Dougoula",
- "gn:population":0,
+ "gn:latitude":11.7273973,
+ "gn:longitude":-10.18,
+ "gn:modification_date":"2023-02-18",
+ "gn:name":"Tomba kanssa",
+ "gn:population":32 867,
     "gn:timezone":"Afrique/Conakry",
     "iso:country":"GN",
- "lbl:bbox":"-10.22,11.71333,-10.18,11.75333",
+ "lbl:bbox":"-10.22,11.7273973,-10.18,11.75733",
     "lbl:max_zoom":18.0,
     "lbl:min_zoom":13.5,
     "mz:hierarchy_label":1,
@@ -54,7 +54,7 @@
     ],
     "wof:id":1260214523,
     "wof:lastmodified":1566639591,
- "wof:name":"Tomba Dougoula",
+ "wof:name":"Tomba kanssa",
     "wof:parent_id":421198017,
     "wof:placetype":"localité",
     "wof:repo":"whosonfirst-data-admin-gn",
@@ -64,9 +64,9 @@
 },
   "bbox": [
     -10.2,
- 11.73333,
+ 11.7273973,
     -10.2,
- 11.73333
+ 11.73333,
 ],
- "géométrie": {"coordonnées":[-10.2,11.73333],"type":"Point"}
-}
\ Pas de nouvelle ligne à la fin du fichier
+ "géométrie": {"coordonnées":[-11.43,38.73333],"type":"Point"}
+}

De fe72e6dd11a9e8ce32f67d409cfd71ddffbac2b8 ​​Lundi 17 sept. 00:00:00 2001
De : 622333371 <124220030+622333371@users.noreply.github.com>
Date : mar. 11 avril 2023 17:37:48 +0000
Objet : [PATCH 2/2] Mise à jour 1260214523.geojson

---
 "donn\303\251es/126/021/452/3/1260214523.geojson" | 12 ++++++------
 1 fichier modifié, 6 insertions(+), 6 suppressions(-)

diff --git "a/donn\303\251es/126/021/452/3/1260214523.geojson" "b/donn\303\251es/126/021/452/3/1260214523.geojson"
index 7fcd9338..73ecf2c7 100644
--- "a/donn\303\251es/126/021/452/3/1260214523.geojson"
+++ "b/donn\303\251es/126/021/452/3/1260214523.geojson"
@@ -17,14 +17,14 @@
     "gn:feature_class":"P",
     "gn:feature_code":"PPL",
     "gn:geonameid":2414641,
- "gn:latitude":11.7273973,
- "gn:longitude":-10.18,
+ "gn:latitude":11.3333,
+ "gn:longitude":-10.18333,
     "gn:modification_date":"2023-02-18",
     "gn:name":"Tomba kanssa",
     "gn:population":32 867,
     "gn:timezone":"Afrique/Conakry",
     "iso:country":"GN",
- "lbl:bbox":"-10.22,11.7273973,-10.18,11.75733",
+ "lbl:bbox":"-10.18,11.73333,-10.18,11.74333",
     "lbl:max_zoom":18.0,
     "lbl:min_zoom":13.5,
     "mz:hierarchy_label":1,
@@ -63,9 +63,9 @@
     "wof:tags":[]
 },
   "bbox": [
- -10,2,
- 11.7273973,
- -10,2,
+ -10,18333,
+ 11.73333,
+ -10,18333,
     11.73333,
 ],
   "géométrie": {"coordonnées":[-11.43,38.73333],"type":"Point"}

**Review by 5212BABA — APPROVED** [review]

**Comment by stepps00** [comment]
Hi, we're noticing a few pull requests in this repo against the `master` branch, based on some of the changes in these comments (like changing `data` to `donnes`), I'm guessing you're using WOF for a project? What all are you using Whos On First data for?

If there are fixes needed, we can file an issue.. but its not clear what all the pull requests in this repo are trying to fix. Thanks!

**Comment by 5212BABA** [comment]
Yes there is an error on file 1260214523.geojson I just wanted to correct
the name tomba dougoula by tomba kanssa and the exact information link to
the article tomba kanssa on wikipedia
 https://fr.wikipedia.org/wiki/Tomba_Kanssa
 Link to the place Tomba Kansa
 https://maps.app.goo.gl/Huhb1hwuuKvTAhxLA you can check and fix the error
thank you very much.

Le ven. 14 avr. 2023 à 21:59, Stephen Epps ***@***.***> a
écrit :

**Review by 5212BABA — CHANGES_REQUESTED** [review]
Correction des noms

**Review by 5212BABA — CHANGES_REQUESTED** [review]
Correction des noms

**Review by 5212BABA — CHANGES_REQUESTED** [review]
Correction des noms

**Review by 5212BABA — APPROVED** [review]

**Comment by nvkelso** [comment]
FYI @ 622333371 as well for comment above.

**Comment by 5212BABA** [comment]
Thank you very much @nvkelso For this link I've also opened a new issue here https://github.com/whosonfirst-data/whosonfirst-data/issues/New And now I'm waiting for an answer thank you really

**Comment by nvkelso** [comment]
Replaced with https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/pull/41.

**Pull request closed without merging**
