### PR TITLE
Update Tombaguia Foula (geom)

### PR DESCRIPTION
**Pull request by 5212BABA**
Corrected lat/lon coordinates and correct names of this Locality @stepps00

### CODE REVIEW

**Comment by nvkelso** [comment]
Fixed instead via https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/pull/37/files.

But if you want to file another followup PR (new one, not this one) for adjusting the lat/long geometry that'd work too.

**Review by nvkelso — CHANGES_REQUESTED** [review]
See comment

**Comment by stepps00** [comment]
Same comment here - I believe the record in this PR was updated separately to resolve some of these issues. @nvkelso @5212BABA are we OK to close this PR/branch?

**Comment by nvkelso** [comment]
Yes, closing.

**Pull request closed without merging**
